#!/usr/bin/env bash
### fnc-encoder -- Furnace InterstellarEncoder interactive
### Usage: fnc encoder [<command>]
###
### Commands: encoder addr                InterstellarEncoder price info
###           encoder objc                InterstellarEncoder claim tokens
###
set -e

encoder="$(fnc --get-encoder)" 

case $1 in
  addr)
    seth call $encoder "getObjectAddress(uint256)(address)" $2
  ;;
  objc)
    seth call $encoder "getObjectClass(uint256)(uint8)" $2
  ;;
     *) fnc help encoder;    ;;
esac
	
