#!/usr/bin/env bash

set -e

# shellcheck source=lib/common.sh
. "${0%/*}/../../lib/common.sh"

LANDRESOURCEV4_AUTHORITY=$(dapp create src/LandResourceAuthorityV4.sol:LandResourceAuthorityV4 [$PETBASE_PROXY,$TOKENUSE_PROXY,$APOSTLEITEMBAR_PROXY,$LANDITEMBAR_PROXY])

seth send -F $OWNER $LANDRESOURCE_PROXY "setAuthority(address)" $LANDRESOURCEV4_AUTHORITY 
if test $(seth call $LANDRESOURCE_PROXY "authority()(address)") != $LANDRESOURCEV4_AUTHORITY ; then
  (echo "migrate LandResourceAuthorityV4 failed ${auth}"; exit 1;)
fi

allowlist=($PETBASE_PROXY $TOKENUSE_PROXY $APOSTLEITEMBAR_PROXY $LANDITEMBAR_PROXY)
for allow in "${allowlist[@]}"; do
  res=$(seth call $LANDRESOURCEV4_AUTHORITY "whiteList(address)(bool)" $allow)
  if test "$res" != true; then
    (echo "migrate LandResourceAuthorityV4 failed ${allow}"; exit 1;)
  fi
done

addAddress "LANDRESOURCEV4_AUTHORITY" "$LANDRESOURCEV4_AUTHORITY"
echo >&2 "${0##*/}: info: setauthority finished."
