#!/usr/bin/env bash

set -e

# shellcheck source=lib/common.sh
. "${0%/*}/../../lib/common.sh"

DRILLLUCKYBOX=$(dapp create src/DrillLuckyBox.sol:DrillLuckyBox $SETTINGSREGISTRY $DRILLTAKEBACK $(seth --to-uint256 1617280889))
addAddress "DRILLLUCKYBOX" "$DRILLLUCKYBOX"
