#!/usr/bin/env bash

set -e

p() { printf "%-7s %-50s %-10s\n" "$1" "$2" "$3"; }

grade=$(seth --to-uint16 1)
sig="createDrill(uint16,address)(uint256)"
tx=$(seth send --async "${DRILLBASE_PROXY?}" "$sig" "$grade" "$AUTH" )
echo >&2 -n "${0##*/}: Waiting for transaction receipt..."
block=$(SETH_TICK=true seth receipt "$tx" blockNumber)
block=$(seth --to-hex "$block")
echo >&2

sig="Create(address,uint256,uint16,uint256)"
keccak=$(seth keccak "$(seth --from-ascii $sig)")
logs=$(seth rpc eth_getLogs -- \
  -n {} \
    -s "${DRILLBASE_PROXY?}" -i address \
    -s "$block"      -i fromBlock \
    -s "$block"      -i toBlock \
  -n [] \
    -s "$keccak" -i append \
  -i topics \
  -i append | echo "[$(paste -sd , -)]")
drillId=$(echo "$logs" | jshon -a -e topics | jq -r ".[2]")
hash=$(echo "$logs" | jshon -a -e transactionHash -u)

if [ "$hash" == "$tx" ]; then
  echo "$tx"
  p "DrillBase_Proxy"  "$drillId"      "minted"
else
  echo >&2 "${0##*/}: Transaction failed."
  seth >&2 receipt "$tx"
  exit 1
fi

index=$(seth --to-uint256 1)
# seth send $IOBJECTOWNERSHIP_PROXY "setApprovalForAll(address,bool)" $ITEMBASE_PROXY $(seth --to-uint256 1)
address=$TOKEN_WATER
# seth send $TOKEN_WATER "approve(address)" $ITEMBASE_PROXY 
seth send $ITEMBASE_PROXY "enchant(uint256,uint256[],address[])(uint256)" $index [$drillId] [$address] 
