#!/usr/bin/env bash
### fnc-gene -- Furnace gene interactive
### Usage: fnc gene [<command>]
###
### Commands: gene strength          GeneScience  strength info
###
set -ex

gene="${IGENESCIENCE?}" 

case $1 in
  strength)
    landId=$2
    tokens=($TOKEN_GOLD $TOKEN_WOOD $TOKEN_WATER $TOKEN_FIRE $TOKEN_SOIL)
    for token in "${tokens[@]}"; do
      info=$(seth call $APOSTLEBASE_PROXY "getApostleInfo(uint256)(uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256)" $3)
      talent=$(echo $info | cut -d' ' -f 2)
      talent=$(seth --to-uint256 $talent)
      strength=$(seth call $IGENESCIENCE "getStrength(uint256,address,uint256)(uint256)" $talent $token $landId)
      seth --to-fix 18 $strength 
      seth estimate $IGENESCIENCE "getStrength(uint256,address,uint256)(uint256)" $talent $token $landId
    done
  ;;
     *) fnc help gene;    ;;
esac
	
