#!/usr/bin/env bash

set -e

index=$(seth --to-uint256 $2)
token=$OBJECTOWNERSHIP_PROXY
landId=$1
seth send $OBJECTOWNERSHIP_PROXY "setApprovalForAll(address,bool)" $LANDRESOURCE_PROXY $(seth --to-uint256 1)
seth send $LANDRESOURCE_PROXY "equip(uint256,address,uint256,address,uint256)" $landId $4 $index $token $3
