#!/usr/bin/env bash
### fnc-tel -- Furnace metateller interactive
### Usage: fnc tel [<command>]
###
### Commands: tel meta   <addr> <id>        Metateller meta data
###           tel objc   <addr> <id>        Metateller object class extension
###           tel rate   <addr> <id> <ele>  Metateller item rate 
###           tel prefer <addr>             Metateller item info
###           tel ent    <params>           Metateller enchant
###           tel dis    <params>           Metateller disenchant
###
### Example:  fnc itb meta
###           fnc itb objc
set -ex

itb="$(fnc --get-itb)" 

case $1 in
  meta)
    seth call $itb "getMetaData(address,uint256)(uint16,uint16,uint16)" $2 $3
     *) fnc help tel;    ;;
esac
	
