#!/usr/bin/env bash

set -e

# shellcheck source=lib/common.sh
. "${0%/*}/../../lib/common.sh"

loadAddresses

timestamp="$DRILLLUCKYBOX_RELEASE_TIME"
DRILLLUCKYBOX=$(dapp create src/DrillLuckyBox.sol:DrillLuckyBox $SETTINGSREGISTRY $DRILLTAKEBACK $(seth --to-uint256 $timestamp))
addAddress "DRILLLUCKYBOX" "$DRILLLUCKYBOX"
