#!/usr/bin/env bash
### fnc-itb -- Furnace itembase interactive
### Usage: fnc itb [<command>]
###
### Commands: itb meta <id>          Itembase base info 
###           itb objc <id>          Itembase object class extension
###           itb rate <id> <ele>    Itembase item rate 
###           itb item <id>          Itembase item info
###           itb ent  <params>      Itembase enchant
###           itb dis  <params>      Itembase disenchant
###
### Example:  fnc itb meta
###           fnc itb objc
set -ex

itb="$(fnc --get-itb)" 

case $1 in
  meta)
    seth call $itb "getBaseInfo(uint256)(uint16,uint16,uint16)" $2
  ;;
  objc)
    seth call $itb "getObjectClassExt(uint256)(uint16)" $2
  ;;
  rate)
    seth call $itb "getRate(uint256,uint256)(uint256)" $2 $3
  ;;
  item)
    seth call $itb "getObjectClassExt(uint256)(uint16)" $2
  ;;
  ent)
    seth send $itb "enchant(uint256,uint256[],address[],uint256[])" "${@:2}"
  ;;
  dis)
    seth send $itb "disenchant(uint256,uint256)" "${@:2}"
  ;;
     *) fnc help itb;    ;;
esac
	
