#!/usr/bin/env bash

set -e

if [ "$FNC_VERBOSE" ]; then set -x; fi

# shellcheck source=lib/common.sh
. "${0%/*}/../../lib/common.sh"

loadAddresses

# registry=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_ERC721_GEGO")))
# seth send -F $OWNER $SETTINGSREGISTRY "setAddressProperty(bytes32,address)" "$registry" "$TOKEN_GEGO"

# GEGO_ADDR=$(seth call $SETTINGSREGISTRY "addressOf(bytes32)(address)" "$registry")
# if test "$GEGO_ADDR" != $(seth --to-checksum-address "$TOKEN_GEGO"); then
#   (echo "check register ${registry} failed."; exit 1;)
# fi
# echo >&2 "${0##*/}: info: Gego register finished."

FORMULA=$(dapp create src/Formula.sol:Formula)
addAddress "FORMULA" "$FORMULA"
echo >&2 "${0##*/}: info: Formula created."

calldata=$(seth calldata "initialize(address)" $SETTINGSREGISTRY)
FORMULA_PROXY=$(dapp create src/FormulaProxy.sol:FormulaProxy $FORMULA $FURNACEPROXYADMIN $calldata)
addAddress "FORMULA_PROXY" "$FORMULA_PROXY"
echo >&2 "${0##*/}: info: FormulaProxy inited."

# setting registry
fml=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_FORMULA")))
seth send -F $OWNER $SETTINGSREGISTRY "setAddressProperty(bytes32,address)" "$fml" "$FORMULA_PROXY"

FML_ADDR=$(seth call $SETTINGSREGISTRY "addressOf(bytes32)(address)" "$fml")
if test "$FML_ADDR" != $(seth --to-checksum-address "$FORMULA_PROXY") ; then
  (echo "check register ${fml} failed."; exit 1;)
fi
echo >&2 "${0##*/}: info: installerEncoder register finished."
