#!/usr/bin/env bash

set -e

# shellcheck source=lib/common.sh
. "${0%/*}/../../lib/common.sh"

LANDITEMBAR=$(dapp create src/LandItemBar.sol:LandItemBar)
addAddress "LANDITEMBAR" "$LANDITEMBAR"
echo >&2 "${0##*/}: info: LandItemBar created."

# 1
maxAmount=$(seth --to-uint256 5)
calldata=$(seth calldata "initialize(address,uint256)" $ISETTINGSREGISTRY $maxAmount)
LANDITEMBAR_PROXY=$(dapp create src/LandItemBarProxy.sol:LandItemBarProxy $LANDITEMBAR $FURNACEPROXYADMIN $calldata)
addAddress "LANDITEMBAR_PROXY" "$LANDITEMBAR_PROXY"
echo >&2 "${0##*/}: info: LandItemBarProxy inited."

# setting registry
registry=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_LAND_ITEM_BAR")))
seth send -F $OWNER $ISETTINGSREGISTRY "setAddressProperty(bytes32,address)" $registry $LANDITEMBAR_PROXY
if test $(seth call $ISETTINGSREGISTRY "addressOf(bytes32)(address)" $registry) != $LANDITEMBAR_PROXY; then
  (echo "check register ${registry} failed."; exit 1;)
fi
echo >&2 "${0##*/}: info: installerEncoder register finished."

