#!/usr/bin/env bash
### fnc-teller -- Furnace metatellerler interactive
### Usage: fnc teller [<command>]
###
### Commands: teller meta   <addr> <id>                     MetaDataTeller meta data
###           teller objc   <addr> <id>                     MetaDataTeller object class extension
###           teller rate   <addr> <id> <ele>               MetaDataTeller item rate 
###           teller addi   <id> <grade> <rate>             MetaDataTeller addInternalTokenMeta
###           teller addx   <addr> <objc> <grade> <rate>    MetaDataTeller addExternalTokenMeta
###           teller rmi    <id> <grade>                    MetaDataTeller removeInternalTokenMeta
###           teller rmx    <addr>                          MetaDataTeller removeExternalTokenMeta
###
### Example:  fnc teller meta
###           fnc teller objc
set -e

teller="$(fnc --get-teller)" 

case $1 in
  meta)
    seth call $teller "getMetaData(address,uint256)(uint16,uint16,uint16)" $2 $3
  ;;
  rate)
    seth call $teller "getRate(address,uint256,uint256)(uint256)" $2 $3 $4
  ;;
  inter)
    seth call $teller "internalToken2Meta(bytes32,uint16)(uint256)" "${@:2}"
    # fnc teller inter 0x434f4e54524143545f4452494c4c5f4241534500000000000000000000000000 0x0001
  ;;
  exter-objc)
    seth call $teller "getExternalObjectClassExt(address)(uint256)" "${@:2}"
  ;;
  exter-rate)
    seth call $teller "getExternalStrengthRate(address,uint16)(uint256)" "${@:2}"
  ;;
  addi)
    seth send $teller "addInternalTokenMeta(bytes32,uint16,uint256)" "${@:2}"
  ;;
  addx)
    seth send $teller "addExternalTokenMeta(address,uint16,uint16,uint256)" "${@:2}"
  ;;
  rmi)
    seth send $teller "removeInternalTokenMeta(bytes32,uint16)" "${@:2}"
  ;;
  rmx)
    seth send $teller "removeExternalTokenMeta(address)" "${@:2}"
  ;;
     *) fnc help teller;    ;;
esac
	
