#!/usr/bin/env bash

set -e

index=$(seth --to-uint256 0)
total=$(seth call $TOKEN_GEGO "totalSupply()(uint256)")
id=$(seth --to-uint256 $(($total + 1)))
seth send $TOKEN_GEGO "safeMint(address,uint256)" $AUTH $id 

seth send $TOKEN_GEGO "setApprovalForAll(address,bool)" $ITEMBASE_PROXY $(seth --to-uint256 1)
address=$TOKEN_ERC20_GOLD
seth send $TOKEN_ERC20_GOLD "approve(address)	" $ITEMBASE_PROXY 
seth send $ITEMBASE_PROXY "enchant(uint256,uint256,address)(uint256)" $index $id $address 
