#!/usr/bin/env bash

set -e

if [ -z "$1" ]
  then
    echo "No argument supplied"
    exit 1
fi

. $(PWD)/bin/init

index=$(seth --to-uint256 $1)
seth call $FORMULA_PROXY  "formulas(uint256)(bytes32,uint128,uint128,uint16,uint16,uint16,bool)" $index 
