#!/usr/bin/env bash

set -e

. $(PWD)/bin/init

tokenId=0x2a0100010100010100000000000000010000000000000000000000000000011e

attr=$(seth call $LANDBASE_PROXY "getResourceRateAttr(uint256)" $tokenId)
echo $attr
gold_rate=$(seth --to-dec ${attr:62:4})
echo "gold_rate"   "$gold_rate"
wood_rate=$(seth --to-dec ${attr:58:4})
echo "wood_rate"   "$wood_rate"
water_rate=$(seth --to-dec ${attr:54:4})
echo "water_rate" "$water_rate"
fire_rate=$(seth --to-dec ${attr:50:4})
echo "fire_rate"   "$fire_rate"
soil_rate=$(seth --to-dec ${attr:46:4})
echo "soil_rate"   "$soil_rate"

# seth call $LANDBASE_PROXY "tokenId2LandAttr(uint256)" $tokenId
