#!/usr/bin/env bash

set -e

. $(PWD)/bin/init

path=$FNC_CONFIG

formula=$(dapp create src/Formula.sol:Formula)
export FORMULA=$formula

cat $path | jq '.FORMULA = $address' --arg address $FORMULA | sponge $path
echo >&2 "${0##*/}: info: Formula created."

# 1
calldata=$(seth calldata "initialize()")
formulaProxy=$(dapp create src/FormulaProxy.sol:FormulaProxy $FORMULA $FURNACEPROXYADMIN $calldata)
export FORMULA_PROXY=$formulaProxy
cat $path | jq '.FORMULA_PROXY = $address' --arg address $FORMULA_PROXY | sponge $path
echo >&2 "${0##*/}: info: FormulaProxy inited."

# setting registry
fml=$(seth --to-bytes32 $(seth --to-hex $(seth --from-ascii "CONTRACT_FORMULA")))
seth send -F $OWNER $ISETTINGSREGISTRY "setAddressProperty(bytes32,address)" $fml $FORMULA_PROXY 
if test $(seth call $ISETTINGSREGISTRY "addressOf(bytes32)(address)" $fml) != $FORMULA_PROXY; then
  (echo "check register ${fml} failed."; exit 1;)
fi
echo >&2 "${0##*/}: info: installerEncoder register finished."


