#!/usr/bin/env bash

set -e

. $(PWD)/bin/init

landId=0x2a0100010100010100000000000000010000000000000000000000000000011e

tokens=($TOKEN_GOLD $TOKEN_WOOD $TOKEN_WATER $TOKEN_FIRE $TOKEN_SOIL)
for token in "${tokens[@]}"; do
	echo "-----------------------------"
	seth call $LANDRESOURCE_PROXY "land2RSState(uint256,address)(uint256,uint256,uint256)" $landId $token
done

        

