#!/usr/bin/env bash

set -e

. $(PWD)/bin/init

path=$FNC_CONFIG
address=$(dapp create src/ItemBase.sol:ItemBase)
export ITEMBASE=$address
seth send $FURNACEPROXYADMIN "upgrade(address,address)" $ITEMBASE_PROXY $ITEMBASE
cat $path | jq '.ITEMBASE = $address' --arg address $ITEMBASE | sponge $path
