#!/usr/bin/env bash

set -e

. $(PWD)/bin/init

path=$FNC_CONFIG
address=$(dapp create src/DrillLuckyBox.sol:DrillLuckyBox $ISETTINGSREGISTRY $DRILLTAKEBACK $(seth --to-uint256 1605657600))
export DRILLLUCKYBOX=$address
cat $path | jq '.DRILLLUCKYBOX = $address' --arg address $DRILLLUCKYBOX | sponge $path
