#!/usr/bin/env python
# -*- coding: utf-8 -*-

# importing the csv module
import csv
# importing matplotlib module
from matplotlib import pyplot as plt

files = [
    "bin/csv/roi-gold.csv",
    "bin/csv/roi-ring1:1.csv",
    "bin/csv/roi-ring1:3.csv",
    "bin/csv/roi-ring3:1.csv",
    "bin/csv/roi-gold-ring1:1.csv"
]

for index, filename in enumerate(files):
    # initializing the titles and rows list
    fields = []
    rows = []
    # reading csv file
    with open(filename, "r") as csvfile:
        # creating a csv reader object
        csvreader = csv.reader(csvfile)
        # extracting field names through first row
        fields = next(csvreader)
        # extracting each data row one by one
        for row in csvreader:
            rows.append(row)
        # get total number of rows
        print("Total no. of rows: %d" % csvreader.line_num)
    # notice that nrows = number 
    # # x-axis values 
    x = [ idx for idx, v in enumerate(rows) ] 
      
    # # Y-axis values 
    y = [ float(row[-1]) for row in rows ] 
    plt.subplot(len(files) + 1, 1, index+1) 
    plt.plot(x, y) 
      
plt.show() 
