#!/usr/bin/env python
# -*- coding: utf-8 -*-

# importing the csv module
import csv
# importing matplotlib module  
from matplotlib import pyplot as plt 

# my data rows as dictionary objects
mydict = []
# Daily ROI of GOLD: x * y% / a0
x = 1.1649
for y in range(1, 10):
    for a0 in range(50, 550, 10):
        gold = x * y / 100.0
        roi = x * y / a0
        row = {
            "ApostleStrength": x,
            "DrillStrength(%)": y,
            "CostOfGold": a0,
            "YielfOfGold": round(gold, 4),
            "DailyROI(%)": round(roi, 3),
            "WeeklyROI(%)": round(roi * 7, 3),
            "YearlyROI(%)": round(roi * 365, 3)
        }
        mydict.append(row)
# field names
fields = [
    "ApostleStrength",
    "DrillStrength(%)",
    "CostOfGold",
    "YielfOfGold",
    "DailyROI(%)",
    "WeeklyROI(%)",
    "YearlyROI(%)"
]
# name of csv file
filename = "bin/csv/roi-gold.csv"
# writing to csv file
with open(filename, "w") as csvfile:
    # creating a csv dict writer object
    writer = csv.DictWriter(csvfile, fieldnames=fields)
    # writing headers (field names)
    writer.writeheader()
    # writing data rows
    writer.writerows(mydict)

# x-axis values 
x = [ idx for idx, v in enumerate(mydict) ] 
  
# Y-axis values 
y = [ row["YearlyROI(%)"] for row in mydict ] 
  
# Function to plot 
plt.plot(x,y) 
  
# function to show the plot 
plt.show() 
